site_name: Equinox OS
site_description: Equinox Operating System Documentation
site_url: https://amnottdevv.github.io/Equinox-os/
repo_url: https://github.com/amnottdevv/Equinox-os
repo_name: amnottdevv/Equinox-os
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.select

plugins:
  - search:
      lang: en

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
  - md_in_html
  - tables

nav:
  - Home: index.md
  - Getting Started: GETTING_STARTED.md
  - Installation: INSTALL.md
  - Architecture: ARCHITECTURE.md
  - Configuration: CONFIGURATION.md
  - Commands: COMMANDS.md
  - Drivers: DRIVERS.md
  - Networking: NETWORKING.md
  - Packages: PACKAGES.md
  - QFS: QFS.md
  - System Calls: SYSCALLS.md
  - Self Hosting: SELF_HOSTING.md
  - Release Notes: RELEASE_NOTES.md
