/* ============================================================================
 *  doomgeneric_morphos.c — DOOM on Equinox OS (v10.10, Phase C)
 * ----------------------------------------------------------------------------
 *  Platform layer for doomgeneric over the Equinox OS int 0x80 syscall ABI:
 *
 *    DG_Init        -> nothing (VESA 32bpp mode already active; the kernel
 *                      blit path validates per-frame anyway)
 *    DG_DrawFrame   -> upload palette (only when I_SetPalette flagged a
 *                      change) then ONE SYS_BLIT: the kernel converts the
 *                      8bpp 320x200 CMAP256 buffer to 32bpp and scales it
 *                      into a centered 4:3 letterbox (classic DOOM look).
 *                      Optional -fps: prints the measured frame rate to
 *                      the console once per second.
 *    DG_SleepMs     -> SYS_SLEEP
 *    DG_GetTicksMs  -> SYS_GETTICK * 10 (100 Hz tick)
 *    DG_GetKey      -> SYS_KEYEVENT (press AND release, RAW key codes,
 *                      translated to doomkeys.h codes like the DOS
 *                      at_to_doom table did) + modern bindings:
 *                        W/S = forward/back, A/D = strafe, Q/E = turn,
 *                        left mouse = fire, right mouse = next weapon,
 *                        ` (backquote) = screenshot /shotNNN.ppm
 *    DG_GetMouse    -> SYS_MOUSEDELTA #33: relative PS/2 deltas + buttons.
 *                      Injected by i_input.c as ev_mouse (horizontal turn
 *                      only — vanilla mouse-y move is disabled on purpose).
 *    DG_SetWindowTitle -> stub
 *
 *  Entry: _start (section .start, offset 0 of the .mrp image) builds
 *  argc/argv from SYS_GETARGS — the shell `doom` command passes
 *  "-iwad /doom1.wad" by default — then calls doomgeneric_Create().
 * ============================================================================ */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#include "doomgeneric.h"
#include "doomkeys.h"
#include "doomdef.h"
#include "doomstat.h"
#include "i_video.h"
#include "m_argv.h"

/* i_video.c, CMAP256 mode: set by I_SetPalette (gamma already applied) */
extern boolean palette_changed;
extern struct color colors[256];

/* ---------------------------------------------------------------
 *  Raw syscall wrappers (int 0x80) — same ABI as syscall.h.
 * --------------------------------------------------------------- */
static inline int msc0(int num) {
    int ret;
    __asm__ volatile("int $0x80" : "=a"(ret) : "a"(num) : "memory", "cc");
    return ret;
}
static inline int msc1(int num, uint32_t a1) {
    int ret;
    __asm__ volatile("int $0x80"
                     : "=a"(ret) : "a"(num), "b"(a1) : "memory", "cc");
    return ret;
}
static inline int msc2(int num, uint32_t a1, uint32_t a2) {
    int ret;
    __asm__ volatile("int $0x80"
                     : "=a"(ret) : "a"(num), "b"(a1), "c"(a2)
                     : "memory", "cc");
    return ret;
}
static inline int msc3(int num, uint32_t a1, uint32_t a2, uint32_t a3) {
    int ret;
    __asm__ volatile("int $0x80"
                     : "=a"(ret) : "a"(num), "b"(a1), "c"(a2), "d"(a3)
                     : "memory", "cc");
    return ret;
}

#define MORPH_SYS_EXIT      1
#define MORPH_SYS_GETARGS  15
#define MORPH_SYS_GETTICK  13
#define MORPH_SYS_SLEEP    14
#define MORPH_SYS_BLIT     30
#define MORPH_SYS_SETPAL   31
#define MORPH_SYS_KEYEVENT 32
#define MORPH_SYS_MOUSEDELTA 33   /* v10.10 Phase C: (int32 dxdy[2]) -> btn */

#define MORPH_BLIT_ASPECT43 0x1u

/* Equinox OS RAW key codes (getkey_event decoder, stdio.cpp v10.9) */
#define MK_UP    (-1)
#define MK_DOWN  (-2)
#define MK_LEFT  (-3)
#define MK_RIGHT (-4)
#define MK_HOME  (-5)
#define MK_END   (-6)
#define MK_PGUP  (-7)
#define MK_PGDN  (-8)
#define MK_DEL   (-9)
#define MK_CTRL  (-10)
#define MK_SHIFT (-11)
#define MK_ALT   (-12)
#define MK_F(n)  (-(12 + (n)))    /* F1 = -13 ... F12 = -24 */

/* Mouse buttons reported by SYS_MOUSEDELTA (kernel morph_mouse_t) */
#define MB_LEFT   0x1u
#define MB_RIGHT  0x2u
#define MB_MIDDLE 0x4u

/* ---------------------------------------------------------------
 *  Options (parsed from argv by morph_start)
 * --------------------------------------------------------------- */
static int opt_fps = 0;            /* -fps: print frame rate once per sec */

/* ---------------------------------------------------------------
 *  Synthetic key events — generated by the mouse button handlers
 *  (fire = KEY_FIRE press/release, next weapon = digit key tap).
 *  DG_GetKey drains this queue BEFORE polling the kernel.
 * --------------------------------------------------------------- */
#define SYNQ_MAX 16
static struct { int pressed; unsigned char key; } synq[SYNQ_MAX];
static int synq_head = 0, synq_tail = 0;

static void syn_post(int pressed, unsigned char key) {
    int next = (synq_head + 1) % SYNQ_MAX;
    if (next == synq_tail) return;              /* full: drop (harmless) */
    synq[synq_head].pressed = pressed;
    synq[synq_head].key = key;
    synq_head = next;
}

/* ---------------------------------------------------------------
 *  FPS counter (-fps): counted in DG_DrawFrame, printed once/sec.
 * --------------------------------------------------------------- */
static uint32_t fps_frames = 0;
static uint32_t fps_last_ms = 0;
static uint32_t fps_total = 0;      /* accumulated — never reset (read
                                    * via QEMU memory peek for precise
                                    * measurement) */

/* ---------------------------------------------------------------
 *  Screenshot (` key): dumped from DG_ScreenBuffer + colors[] as
 *  binary PPM (P6) into the RAMFS root via libc FILE* (full-buffer
 *  mode -> SYS_MKFILE at fclose).
 * --------------------------------------------------------------- */
static int shot_pending = 0;
static int shot_number = 0;

static void save_screenshot(void) {
    char name[24];
    int w = DOOMGENERIC_RESX, h = DOOMGENERIC_RESY;

    if (shot_number >= 999) return;
    snprintf(name, sizeof(name), "/shot%03d.ppm", ++shot_number);

    FILE* f = fopen(name, "w");
    if (!f) {
        printf("[shot] failed to open %s\r\n", name);
        return;
    }
    fprintf(f, "P6\n%d %d\n255\n", w, h);
    for (int y = 0; y < h; y++) {
        unsigned char row[3 * 512];
        const unsigned char* s = DG_ScreenBuffer + (size_t)y * w;
        for (int x = 0; x < w; x++) {
            const unsigned char* c = (const unsigned char*)&colors[s[x]];
            row[x * 3 + 0] = c[2];              /* colors[] is 0x00BBGGRR */
            row[x * 3 + 1] = c[1];
            row[x * 3 + 2] = c[0];
        }
        fwrite(row, 1, (size_t)w * 3, f);
    }
    fclose(f);
    printf("[shot] saved: %s\r\n", name);
}

/* ---------------------------------------------------------------
 *  Next-weapon cycle (right mouse button).
 *  DOOM has no "next weapon" key in vanilla — we synthesize a digit
 *  key press for the next owned weapon slot, exactly what a player
 *  would do manually.
 * --------------------------------------------------------------- */
static void post_next_weapon(void) {
    player_t* pl = &players[consoleplayer];
    int cur = (pl->pendingweapon != wp_nochange) ? pl->pendingweapon
                                                 : pl->readyweapon;
    for (int i = 1; i <= NUMWEAPONS; i++) {
        int w = (cur + i) % NUMWEAPONS;
        if (pl->weaponowned[w]) {
            unsigned char digit = (unsigned char)('1' + w);
            syn_post(1, digit);
            syn_post(0, digit);
            return;
        }
    }
}

/* ---------------------------------------------------------------
 *  DG platform hooks
 * --------------------------------------------------------------- */
void DG_Init(void) {
    /* Graphics are set up by the kernel (VESA 32bpp + blit syscalls);
     * the first DG_DrawFrame uploads the palette. Nothing to do. */
}

void DG_DrawFrame(void) {
    if (palette_changed) {
        uint8_t pal[768];
        for (int i = 0; i < 256; i++) {
            pal[i * 3 + 0] = (uint8_t)colors[i].r;
            pal[i * 3 + 1] = (uint8_t)colors[i].g;
            pal[i * 3 + 2] = (uint8_t)colors[i].b;
        }
        msc1(MORPH_SYS_SETPAL, (uint32_t)(uintptr_t)pal);
        palette_changed = false;
    }

    if (shot_pending) {
        shot_pending = 0;
        save_screenshot();
    }

    uint32_t dims = ((uint32_t)(uint16_t)DOOMGENERIC_RESY << 16)
                  | (uint32_t)(uint16_t)DOOMGENERIC_RESX;
    msc3(MORPH_SYS_BLIT, (uint32_t)(uintptr_t)DG_ScreenBuffer, dims,
         MORPH_BLIT_ASPECT43);

    if (opt_fps) {
        fps_frames++;
        fps_total++;
        uint32_t now = DG_GetTicksMs();
        if (now - fps_last_ms >= 1000u) {
            uint32_t secs = (now - fps_last_ms) / 1000u;
            printf("[fps] %lu.%lu\r\n",
                   (unsigned long)(fps_frames / secs),
                   (unsigned long)((fps_frames % secs) * 10 / secs));
            fps_frames = 0;
            fps_last_ms = now;
        }
    }
}

void DG_SleepMs(uint32_t ms) {
    msc1(MORPH_SYS_SLEEP, ms);
}

uint32_t DG_GetTicksMs(void) {
    return (uint32_t)msc0(MORPH_SYS_GETTICK) * 10u;   /* 100 Hz tick */
}

void DG_SetWindowTitle(const char* title) {
    (void)title;   /* single process, no window manager */
}

/* ---------------------------------------------------------------
 *  DG_GetMouse — relative deltas + button state (SYS_MOUSEDELTA).
 *  Returns 1 when the syscall succeeded. The caller (i_input.c)
 *  posts an ev_mouse event; horizontal mouse-y is intentionally
 *  zeroed (vanilla "mouse forward" motion trips players up).
 * --------------------------------------------------------------- */
int DG_GetMouse(int* dx, int* dy, int* buttons) {
    int32_t dxdy[2] = { 0, 0 };
    int btn = msc1(MORPH_SYS_MOUSEDELTA, (uint32_t)(uintptr_t)dxdy);
    if (btn < 0 || btn > 7) {
        /* kernel without syscall #33 (pre-v10.10): mouse unavailable */
        if (dx) *dx = 0;
        if (dy) *dy = 0;
        if (buttons) *buttons = 0;
        return 0;
    }
    if (dx) *dx = dxdy[0];
    if (dy) *dy = dxdy[1];          /* reported raw; i_input.c decides use */
    if (buttons) *buttons = btn;
    (void)dy;
    return 1;
}

/* Equinox OS RAW code -> DOOM key (mirrors the DOS at_to_doom table:
 * Ctrl = KEY_FIRE, Space = KEY_USE, arrows/F-keys as their codes)
 * PLUS modern bindings: WASD movement, QE turning. */
static unsigned char translate_doom_key(int mk) {
    switch (mk) {
        case MK_UP:     return KEY_UPARROW;      /* 0xad */
        case MK_DOWN:   return KEY_DOWNARROW;    /* 0xaf */
        case MK_LEFT:   return KEY_LEFTARROW;    /* 0xac */
        case MK_RIGHT:  return KEY_RIGHTARROW;   /* 0xae */
        case MK_HOME:   return KEY_HOME;
        case MK_END:    return KEY_END;
        case MK_PGUP:   return KEY_PGUP;
        case MK_PGDN:   return KEY_PGDN;
        case MK_DEL:    return KEY_DEL;
        case MK_CTRL:   return KEY_FIRE;         /* default key_fire   */
        case MK_SHIFT:  return KEY_RSHIFT;       /* default key_speed  */
        case MK_ALT:    return KEY_RALT;         /* default key_strafe */
        case 27:        return KEY_ESCAPE;
        case '\n':                              /* 10, Equinox OS Enter   */
        case '\r':      return KEY_ENTER;        /* 13                 */
        case '\b':      return KEY_BACKSPACE;    /* 0x7f               */
        case '\t':      return KEY_TAB;
        case ' ':       return KEY_USE;          /* default key_use    */
        case 'w':       return KEY_UPARROW;      /* modern: forward    */
        case 's':       return KEY_DOWNARROW;    /* modern: back       */
        case 'a':       return KEY_STRAFE_L;     /* modern: strafe L   */
        case 'd':       return KEY_STRAFE_R;     /* modern: strafe R   */
        case 'q':       return KEY_LEFTARROW;    /* modern: turn L     */
        case 'e':       return KEY_RIGHTARROW;   /* modern: turn R     */
        default:
            if (mk >= MK_F(1) && mk <= MK_F(10))
                return (unsigned char)(0x80 + 0x3b + ((-mk) - 13));
            if (mk == MK_F(11)) return (unsigned char)(0x80 + 0x57);
            if (mk == MK_F(12)) return (unsigned char)(0x80 + 0x58);
            if (mk > 0 && mk <= 126)
                return (unsigned char)mk;        /* raw unshifted ASCII */
            return 0;
    }
}

int DG_GetKey(int* pressed, unsigned char* key) {
    /* 1. synthetic events (mouse buttons) take priority */
    if (synq_tail != synq_head) {
        *pressed = synq[synq_tail].pressed;
        *key = synq[synq_tail].key;
        synq_tail = (synq_tail + 1) % SYNQ_MAX;
        return 1;
    }

    /* 2. kernel keyboard queue */
    int v = msc0(MORPH_SYS_KEYEVENT);
    if (v == 0) return 0;                    /* queue empty            */
    *pressed = (v >> 16) & 1;
    int mk = (int)(int16_t)(uint16_t)(v & 0xFFFFu);

    /* ` = screenshot request (never forwarded to the engine) */
    if (mk == '`') {
        if (*pressed) shot_pending = 1;
        return 0;                            /* re-poll next tick      */
    }

    unsigned char dk = translate_doom_key(mk);
    if (dk == 0) return 0;                   /* untranslatable: skip   */
    *key = dk;
    return 1;
}

/* ---------------------------------------------------------------
 *  Mouse button edges -> synthetic DOOM keys. Called from
 *  i_input.c right after DG_GetMouse so button state and motion
 *  stay in the same input pass.
 * --------------------------------------------------------------- */
static uint32_t prev_buttons = 0;

void DG_MouseButtons(int buttons) {
    uint32_t rising = (uint32_t)buttons & ~prev_buttons;
    uint32_t falling = ~((uint32_t)buttons) & prev_buttons;
    prev_buttons = (uint32_t)buttons;

    if (rising & MB_LEFT)   syn_post(1, KEY_FIRE);
    if (falling & MB_LEFT)  syn_post(0, KEY_FIRE);
    if (rising & MB_RIGHT)  post_next_weapon();
}

/* ---------------------------------------------------------------
 *  .mrp entry is the asm stub in doom_start.S (jmp morph_start).
 *  The shell `doom` command sets e.g. "-iwad /doom1.wad" via
 *  SYS_GETARGS; we split it into argv[] and hand it to DOOM.
 * --------------------------------------------------------------- */
extern void doomgeneric_Create(int argc, char** argv);
extern void M_FindResponseFile(void);
extern void D_DoomMain(void);

void morph_start(void* legacy_api) {
    (void)legacy_api;                        /* pure-syscall program   */

    static char args[256];
    static char* argv[40];
    int argc = 0;

    argv[argc++] = (char*)"doom";
    int n = msc2(MORPH_SYS_GETARGS, (uint32_t)(uintptr_t)args,
                 (uint32_t)sizeof(args));
    for (int i = 0; i < n && argc < 40; ) {
        while (i < n && (args[i] == ' ' || args[i] == '\t')) i++;
        if (i >= n || args[i] == '\0') break;
        argv[argc++] = &args[i];
        while (i < n && args[i] != ' ' && args[i] != '\t' &&
               args[i] != '\0') i++;
        if (i < n) args[i++] = '\0';
    }

    /* -fps: frame-rate probe (Phase C performance work) */
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] == '-' && argv[i][1] == 'f' && argv[i][2] == 'p'
            && argv[i][3] == 's' && argv[i][4] == '\0') {
            opt_fps = 1;
            fps_last_ms = 0;
            printf("[fps] counter enabled\r\n");
        }
    }

    doomgeneric_Create(argc, argv);

    /* doomgeneric's D_DoomMain RETURNS after engine setup — the port
     * owns the frame loop (same as doomgeneric_soso/win/xlib mains):
     * one Tick = input poll + tics + D_Display (blit). Never returns;
     * quitting happens via I_Quit -> exit() -> SYS_EXIT. */
    for (;;) {
        doomgeneric_Tick();
    }
}
