/*
 * ============================================================================
 *  blittest.cpp — v10.9 Fase A regression (hosted Morph.h program)
 * ----------------------------------------------------------------------------
 *  Validates the three kernel pieces DOOM needs, from ring 3:
 *
 *   1. FAST BLIT PATH (syscalls 30/31)
 *      - set_palette(): 256-entry RGB upload
 *      - blit(): 8bpp buffer -> full screen 32bpp, nearest-neighbor scale
 *      - animated gradient + moving bar for ~100 frames, timing each frame
 *        (gettick is 100 Hz; report frames/sec)
 *      - letterbox 4:3 variant drawn too (SYS_BLIT_ASPECT43)
 *
 *   2. BIG USER ARENA (33 MB)
 *      - malloc() one 16 MB block + touch every page (proves the paging
 *        U/S map covers the expanded arena; a too-small arena returns 0)
 *
 *   3. WAD MODULE PATH (zero-copy big file)
 *      - file_size("/bigtest.bin") must match the expected size
 *      - file_read_all() of the header + rolling checksum over the whole
 *        file (proves supervisor staging memory is readable via syscalls)
 *
 *  Expected output ends with:  BLITTEST PASS
 * ============================================================================
 */

#include "Morph.h"

#define SRC_W 320
#define SRC_H 200
#define FRAMES 100

static uint8_t frame[SRC_W * SRC_H];
static uint8_t pal[768];

/* .mrp entry: section .start at offset 0 (an mrp_pack.py requirement). */
extern "C" __attribute__((section(".start")))
void _start(void* legacy_api) {
    (void)legacy_api;   /* pure syscalls — the legacy argument is ignored */
    print("blittest: v10.9 fast-blit + big-arena + wad-path regression\n");
    print("blittest: ring=");
    printint((uint32_t)ring());
    print("\n");

    /* ---------- 1. framebuffer ---------- */
    morph_fbinfo_t fb;
    fb_info(&fb);
    if (!fb.avail) {
        print("blittest: FAIL no graphics mode\n");
        exit(1);
    }
    print("blittest: fb ");
    printint(fb.width);
    print("x");
    printint(fb.height);
    print(" bpp=");
    printint(fb.bpp);
    print(" pitch=");
    printint(fb.pitch);
    print("\n");

    /* ---------- 2. big arena: 16 MB malloc + page touch ---------- */
    uint32_t big_mb = 16u;
    uint8_t* big = (uint8_t*)malloc(big_mb * 1024u * 1024u);
    if (!big) {
        print("blittest: FAIL 16MB malloc returned 0 (arena too small?)\n");
        exit(1);
    }
    /* Touch one byte per 4 KB page — unmapped pages would #PF and kill us. */
    for (uint32_t off = 0; off < big_mb * 1024u * 1024u; off += 4096) {
        big[off] = (uint8_t)(off >> 12);
    }
    for (uint32_t off = 0; off < big_mb * 1024u * 1024u; off += 4096) {
        if (big[off] != (uint8_t)(off >> 12)) {
            print("blittest: FAIL big-arena verify at offset\n");
            exit(1);
        }
    }
    print("blittest: 16MB arena malloc + verify OK\n");

    /* ---------- 3. WAD path: zero-copy big file ---------- */
    int bsize = file_size("/bigtest.wad");
    if (bsize != 300000) {            /* generated by qemu_v109_test.py */
        print("blittest: FAIL /bigtest.wad size=");
        printint((uint32_t)bsize);
        print(" (expected 300000)\n");
        exit(1);
    }
    /* Rolling checksum over the whole file in 32 KB chunks. */
    uint8_t* rbuf = (uint8_t*)malloc(32768);
    if (!rbuf) { print("blittest: FAIL read buf alloc\n"); exit(1); }
    int fd = file_open("/bigtest.wad");
    if (fd < 0) { print("blittest: FAIL open /bigtest.wad\n"); exit(1); }
    uint32_t sum = 1;
    int total = 0;
    for (;;) {
        int n = file_read(fd, rbuf, 32768);
        if (n <= 0) break;
        total += n;
        for (int i = 0; i < n; i++) {
            sum = (sum * 31u) + rbuf[i];
        }
    }
    file_close(fd);
    if (total != 300000) {
        print("blittest: FAIL wad-path read total=");
        printint((uint32_t)total);
        print("\n");
        exit(1);
    }
    print("blittest: /bigtest.bin 300000 bytes via zero-copy path, sum=");
    printint(sum);
    print("\n");

    /* ---------- 4. palette ---------- */
    for (int i = 0; i < 256; i++) {
        pal[i * 3 + 0] = (uint8_t)i;               /* R ramp          */
        pal[i * 3 + 1] = (uint8_t)(255 - i);       /* G inverse ramp  */
        pal[i * 3 + 2] = (uint8_t)((i * 7) & 0xFF);/* B bands         */
    }
    if (set_palette(pal) != 0) {
        print("blittest: FAIL set_palette\n");
        exit(1);
    }

    /* ---------- 5. animated blit (full stretch) ---------- */
    uint32_t t0 = gettick();
    for (int f = 0; f < FRAMES; f++) {
        int bar_x = (f * 5) % (SRC_W - 40);
        for (int y = 0; y < SRC_H; y++) {
            uint8_t* row = frame + y * SRC_W;
            uint8_t base = (uint8_t)(y + f);
            for (int x = 0; x < SRC_W; x++) {
                row[x] = (uint8_t)(base + (x >> 2));
            }
        }
        for (int y = 20; y < 60; y++) {
            for (int x = bar_x; x < bar_x + 40; x++) {
                frame[y * SRC_W + x] = 0xC0;
            }
        }
        if (blit(frame, SRC_W, SRC_H, MORPH_BLIT_STRETCH) != 0) {
            print("blittest: FAIL blit stretch\n");
            exit(1);
        }
    }
    uint32_t t1 = gettick();
    uint32_t ms = (t1 - t0) * 10u;                 /* 100 Hz tick */
    print("blittest: ");
    printint(FRAMES);
    print(" stretch frames in ");
    printint(ms);
    print(" ms (");
    if (ms > 0) { printint((uint32_t)(FRAMES * 1000u / ms)); }
    else { print("9999"); }
    print(" fps)\n");

    /* ---------- 6. letterbox 4:3 variant ---------- */
    for (int f = 0; f < 20; f++) {
        for (int y = 0; y < SRC_H; y++) {
            uint8_t* row = frame + y * SRC_W;
            for (int x = 0; x < SRC_W; x++) {
                row[x] = (uint8_t)((x ^ y) + f * 3);
            }
        }
        if (blit(frame, SRC_W, SRC_H, MORPH_BLIT_ASPECT43) != 0) {
            print("blittest: FAIL blit aspect43\n");
            exit(1);
        }
    }
    print("blittest: aspect43 letterbox OK\n");

    /* Final summary — printed AFTER the animation, because blit frames
     * paint over the whole LFB and erase earlier console lines. */
    print("blittest: SUMMARY arena=16MB wad=300000 sum=");
    printint(sum);
    print(" frames=");
    printint((uint32_t)FRAMES);
    print("\n");

    /* Leave the last blit frame on screen — the shell redraws its prompt
     * on top. (Clearing would erase the console text of this program's
     * own report lines too: they live in the same LFB.) */

    print("BLITTEST PASS\n");
    exit(0);
}
