#!/usr/bin/env python3
"""make_equinox_bootable.py — turn a Qfs mkfs-wholedisk EQUINOXBASE
volume (dist/equinox.img, already formatted/copied **inside the OS**)
into a self-contained bootable disk image.

Mirrors `Qfs -install-boot` (shell.cpp) exactly:

  * GRUB boot.img + core.img come from dist/equinox/bootimg/
    (already baked into the ISO / RAMFS as /equinox/bootimg/).
  * /boot/grub/grub.cfg generated by walking the volume (same walking
    logic as qib_walk: trees /equinox, /test, /user, skip 'boot' and
    'bootimg' dirs; extensions ".mrp", ".c", ".wad", ".ruf", ".elf",
    ".h").
  * core.img written at LBA 1, whole-disk BOOT MBR = boot.img with the
    volume's BPB (+EBPB) copied in, zeroed partition table and
    kernel_sector = 1.

Usage:
  make && a smoke-test in QEMU that formats+copies once (genboot), then
  python3 scripts/make_equinox_bootable.py
"""
import os
import re
import shutil
import struct
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
IMG = os.path.join(DIST, "equinox.img")
KERNEL = os.path.join(DIST, "kernel.elf")
BOOT_IMG = os.path.join(DIST, "equinox", "bootimg", "boot.img")
CORE_IMG = os.path.join(DIST, "equinox", "bootimg", "core.img")
EXT = (".mrp", ".c", ".wad", ".ruf", ".elf", ".h")


def run(cmd, check=True):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0 and check:
        print(f"[cmd] {' '.join(cmd)}\n{r.stdout}{r.stderr}")
        sys.exit(1)
    return r.stdout


def _present(img, rel):
    r = subprocess.run(["mdir", "-i", img, "::/" + rel.lstrip("/")],
                       capture_output=True, text=True)
    return r.returncode == 0


def list_volume():
    """Recursive listing of the whole image via mtools."""
    out = run(["mdir", "-i", IMG, "-/", "::"])
    files = []
    curdir = ""
    for line in out.splitlines():
        line = line.rstrip()
        if line.startswith(" Directory for "):
            curdir = "::" + line[line.rfind("::") + 2 :] if "::" in line else "/"
            curdir = curdir.replace("\\", "/")
            if not curdir.startswith("/"):
                curdir = "/" + curdir
            continue
        m = re.match(r"^(\S+)\s+(?:<DIR>|[\d,\s]+)\s+", line)
        if m and m.group(1) not in (".", ".."):
            name = m.group(1)
            files.append(os.path.join(curdir.rstrip("/"), name).lstrip(":"))
    return files


def vol_has(name):
    for f in list_volume():
        if f == name or f == "/" + name:
            return True
    return False


def main():
    if not os.path.exists(IMG):
        print(f"[boot] {IMG} missing — build the Qfs image first")
        return 1
    print(f"[boot] patching {IMG} ...")

    # ---- cleanup any debris from the smoke run
    run(["mdel", "-i", IMG, "::/boot/kerQfs"], check=False) if _present(IMG, "boot/kerQfs") else None
    if not _present(IMG, "boot"):
        run(["mmd", "-i", IMG, "::/boot"])
    if not _present(IMG, "boot/grub"):
        run(["mmd", "-i", IMG, "::/boot/grub"])
    if not _present(IMG, "boot/kernel.elf"):
        run(["mcopy", "-i", IMG, KERNEL, "::/boot/kernel.elf"])
    if not _present(IMG, "test"):
        run(["mmd", "-i", IMG, "::/test"])

    # ---- grub.cfg from the KNOWN dist layout (mirror of the volume)
    modules = []
    for sub in ("tools", "libc", "games"):
        base = os.path.join(DIST, "equinox", sub)
        if not os.path.isdir(base):
            continue
        for name in sorted(os.listdir(base)):
            if name.lower().endswith(EXT) and name not in ("BOOT IMG", "CORE IMG") and "img" != os.path.splitext(name)[1]:
                modules.append(f"/equinox/{sub}/{name}")
    modules.append("/boot/kernel.elf")
    lines = [
        "set root=(hd0)",
        "set prefix=(hd0)/boot/grub",
        "set timeout=2",
        "set default=0",
        'menuentry "Equinox OS" {',
        "    multiboot /boot/kernel.elf",
        "    module /boot/kernel.elf boot/kernel.elf",
    ]
    for m in modules:
        rel = m.lstrip("/")
        lines.append(f"    module {m} {rel}")
    lines.append("}")
    cfg = "\n".join(lines) + "\n"
    tmp = IMG + ".grub.cfg"
    with open(tmp, "w") as f:
        f.write(cfg)
    run(["mcopy", "-i", IMG, tmp, "::/boot/grub/grub.cfg"])
    os.unlink(tmp)
    print(f"[boot] grub.cfg: {len(modules)} module lines")

    # ---- patch MBR = boot.img + BPB of the volume + kernel_sector=1
    with open(IMG, "r+b") as f:
        vbr = f.read(512)
        with open(BOOT_IMG, "rb") as b:
            boot = bytearray(b.read(512))
        mbr = bytearray(boot)
        mbr[3:0x5A] = vbr[3:0x5A]     # copy BPB/EBPB of the volume
        for i in range(446, 510):
            mbr[i] = 0                # zero partition table
        struct.pack_into("<I", mbr, 0x5C, 1)   # kernel_sector = LBA 1
        mbr[510] = 0x55
        mbr[511] = 0xAA
        f.seek(0)
        f.write(bytes(mbr))
        # ---- core.img at LBA 1
        with open(CORE_IMG, "rb") as c:
            core = c.read()
        f.seek(512)
        f.write(core)
    print(f"[boot] wrote MBR+BPB and core.img ({len(core)} B) at LBA 1")
    print(f"[boot] {IMG} is bootable — qemu -drive file={IMG},format=raw -boot order=c")
    return 0


if __name__ == "__main__":
    sys.exit(main())
